# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workout.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser as wb
from Conn_database import *

class Ui_workout_window(object):
    def openwindow(self, workout_window, name):
        videos = get_current_day_workout()
        if name == 'exit':
            from user_screen_ import Ui_user_scr
            self.b_window = QtWidgets.QMainWindow()
            self.ui = Ui_user_scr()
            self.ui.setupUi(self.b_window)
            self.b_window.show()
            workout_window.close()
        elif name == 'demonstration_1':
            wb.open_new(videos[4])
        elif name == 'demonstration_2':
            wb.open_new(videos[5])
        elif name == 'demonstration_3':
            wb.open_new(videos[6])
        elif name == 'demonstration_4':
            wb.open_new(videos[7])

    def setupUi(self, workout_window):
        workout_window.setObjectName("workout_window")
        workout_window.setEnabled(True)
        workout_window.resize(900, 800)
        self.centralwidget = QtWidgets.QWidget(workout_window)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 901, 801))
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/image_4.jpg"))
        self.background.setScaledContents(True)
        self.background.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.background.setObjectName("background")
        self.demonstration_1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda:self.openwindow(workout_window, 'demonstration_1'))
        self.demonstration_1.setGeometry(QtCore.QRect(130, 290, 131, 34))
        self.demonstration_1.setStyleSheet("QPushButton {\n"
"    border: 1px solid white;\n"
"    border-radius: 15px;\n"
"    background-color: #14ccad;\n"
"    min-width: 80px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.demonstration_1.setObjectName("demonstration_1")
        self.demonstration_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda:self.openwindow(workout_window, 'demonstration_2'))
        self.demonstration_2.setGeometry(QtCore.QRect(130, 410, 131, 34))
        self.demonstration_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid white;\n"
"    border-radius: 15px;\n"
"    background-color:#14ccad;\n"
"    min-width: 80px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.demonstration_2.setObjectName("demonstration_2")
        self.demonstration_3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda:self.openwindow(workout_window, 'demonstration_3'))
        self.demonstration_3.setGeometry(QtCore.QRect(130, 530, 131, 34))
        self.demonstration_3.setStyleSheet("QPushButton {\n"
"    border: 1px solid white;\n"
"    border-radius: 15px;\n"
"    background-color: #14ccad;\n"
"    min-width: 80px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.demonstration_3.setObjectName("demonstration_3")
        self.demonstration_4 = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda:self.openwindow(workout_window, 'demonstration_4'))
        self.demonstration_4.setGeometry(QtCore.QRect(130, 650, 131, 34))
        self.demonstration_4.setStyleSheet("QPushButton {\n"
"    border: 1px solid white;\n"
"    border-radius: 15px;\n"
"    background-color:#14ccad;\n"
"    min-width: 80px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.demonstration_4.setObjectName("demonstration_4")
        self.exit = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(workout_window, 'exit'))
        self.exit.setGeometry(QtCore.QRect(400, 720, 112, 34))
        self.exit.setStyleSheet("QPushButton {\n"
"    border: 1px solid white;\n"
"    border-radius: 15px;\n"
"    background-color: red;\n"
"    min-width: 80px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.exit.setObjectName("exit")
        self.exercise_1 = QtWidgets.QLabel(self.centralwidget)
        self.exercise_1.setGeometry(QtCore.QRect(40, 240, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exercise_1.setFont(font)
        self.exercise_1.setStyleSheet("QLabel\n"
"{\n"
"    color:white;\n"
"}")
        self.exercise_1.setText("")
        self.exercise_1.setObjectName("exercise_1")
        self.exercise_2 = QtWidgets.QLabel(self.centralwidget)
        self.exercise_2.setGeometry(QtCore.QRect(40, 360, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exercise_2.setFont(font)
        self.exercise_2.setStyleSheet("QLabel\n"
"{\n"
"    color:white;\n"
"}")
        self.exercise_2.setText("")
        self.exercise_2.setObjectName("exercise_2")
        self.exercise_3 = QtWidgets.QLabel(self.centralwidget)
        self.exercise_3.setGeometry(QtCore.QRect(40, 480, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exercise_3.setFont(font)
        self.exercise_3.setStyleSheet("QLabel\n"
"{\n"
"    color:white;\n"
"}")
        self.exercise_3.setText("")
        self.exercise_3.setObjectName("exercise_3")
        self.exercise_4 = QtWidgets.QLabel(self.centralwidget)
        self.exercise_4.setGeometry(QtCore.QRect(40, 600, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exercise_4.setFont(font)
        self.exercise_4.setStyleSheet("QLabel\n"
"{\n"
"    color:white;\n"
"}")
        self.exercise_4.setText("")
        self.exercise_4.setObjectName("exercise_4")
        workout_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(workout_window)
        QtCore.QMetaObject.connectSlotsByName(workout_window)

    def retranslateUi(self, workout_window):
        _translate = QtCore.QCoreApplication.translate
        workout_window.setWindowTitle(_translate("workout_window", "MainWindow"))
        self.demonstration_1.setText(_translate("workout_window", "Demonstration"))
        self.demonstration_2.setText(_translate("workout_window", "Demonstration"))
        self.demonstration_3.setText(_translate("workout_window", "Demonstration"))
        self.demonstration_4.setText(_translate("workout_window", "Demonstration"))
        self.exit.setText(_translate("workout_window", "EXIT"))
import app_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    workout_window = QtWidgets.QMainWindow()
    ui = Ui_workout_window()
    ui.setupUi(workout_window)
    workout_window.show()
    sys.exit(app.exec_())
